<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><OutputType>Exe</OutputType><AssemblyName>FDull.Cli</AssemblyName><PackageId>FDull.Tool</PackageId>
    <PackAsTool>true</PackAsTool><ToolCommandName>fdull</ToolCommandName><IsPackable>true</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../FDull/FDull.fsproj" />
    <ProjectReference Include="../FDull.Worker/FDull.Worker.fsproj" ReferenceOutputAssembly="false" Private="false" />
    <None Include="../../README.md" Pack="true" PackagePath="/" />
    <Compile Include="Program.fs" />
  </ItemGroup>
</Project>
