namespace FDull

open System
open System.IO
open System.Text.RegularExpressions

/// Exact generated-source profiles reviewed against supported SDK and test tooling versions.
module internal WorkspaceGenerated =
    let private normalizedPath (path: string) = path.Replace('\\', '/')

    let private endsWith suffix (path: string) =
        (normalizedPath path).EndsWith(suffix, StringComparison.OrdinalIgnoreCase)

    let private text path =
        File.ReadAllText(path).Replace("\r\n", "\n", StringComparison.Ordinal)

    let isTestSdkProgram file =
        endsWith "/microsoft.net.test.sdk/17.14.1/build/net8.0/Microsoft.NET.Test.Sdk.Program.fs" file

    let isXunitDefaultReporters file =
        endsWith "/xunit.v3.core/3.1.0/_content/DefaultRunnerReporters.fs" file

    let isXunitEntryPoint (file: string) =
        Path.GetFileName(file) = "XunitAutoGeneratedEntryPoint.fs"

    let isTestingPlatformExtensions (file: string) =
        Path.GetFileName(file) = "SelfRegisteredExtensions.fs"

    let private hasReference suffix references =
        references |> List.exists (endsWith suffix)

    let private defaultRunnerReporters =
        [ "// <auto-generated> This file has been auto generated by xunit.v3.core. </auto-generated>"
          ""
          "module internal XunitDefaultRunnerReporters"
          ""
          "[<assembly: global.Xunit.Runner.Common.RegisterRunnerReporter(typeof<global.Xunit.Runner.Common.AppVeyorReporter>)>]"
          "[<assembly: global.Xunit.Runner.Common.RegisterRunnerReporter(typeof<global.Xunit.Runner.Common.DefaultRunnerReporter>)>]"
          "[<assembly: global.Xunit.Runner.Common.RegisterRunnerReporter(typeof<global.Xunit.Runner.Common.JsonReporter>)>]"
          "[<assembly: global.Xunit.Runner.Common.RegisterRunnerReporter(typeof<global.Xunit.Runner.Common.QuietReporter>)>]"
          "[<assembly: global.Xunit.Runner.Common.RegisterRunnerReporter(typeof<global.Xunit.Runner.Common.SilentReporter>)>]"
          "[<assembly: global.Xunit.Runner.Common.RegisterRunnerReporter(typeof<global.Xunit.Runner.Common.TeamCityReporter>)>]"
          "[<assembly: global.Xunit.Runner.Common.RegisterRunnerReporter(typeof<global.Xunit.Runner.Common.VerboseReporter>)>]"
          "[<assembly: global.Xunit.Runner.Common.RegisterRunnerReporter(typeof<global.Xunit.Runner.Common.VstsReporter>)>]"
          "do ()"
          "" ]
        |> String.concat "\n"

    let private validNamespace (value: string) =
        let validPart (part: string) =
            let rec validAt index =
                index = part.Length
                || ((Char.IsLetterOrDigit part[index] || part[index] = '_') && validAt (index + 1))

            not (String.IsNullOrWhiteSpace part) && Char.IsLetter(part[0]) && validAt 1

        not (String.IsNullOrWhiteSpace value)
        && (value.Split('.') |> Array.toList |> List.forall validPart)

    let private testingPlatformExtensions rootNamespace hooks =
        [ "//------------------------------------------------------------------------------"
          "// <auto-generated>"
          "//     This code was generated by Microsoft.Testing.Platform.MSBuild"
          "// </auto-generated>"
          "//------------------------------------------------------------------------------"
          ""
          "namespace " + rootNamespace
          ""
          "open System.Runtime.CompilerServices"
          ""
          "[<System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage>]"
          "[<Extension>]"
          "type SelfRegisteredExtensions() ="
          ""
          "    [<Extension>]"
          "    static member AddSelfRegisteredExtensions (builder: Microsoft.Testing.Platform.Builder.ITestApplicationBuilder, args: string[]) =" ]
        @ (hooks
           |> List.map (fun hook -> "        " + hook + ".AddExtensions(builder, args)"))
        |> String.concat "\n"

    let private xunitEntryPoint rootNamespace =
        [ "// <auto-generated> This file has been auto generated by xunit.v3.msbuildtasks. </auto-generated>"
          ""
          "module internal " + rootNamespace + ".AutoGenerated"
          ""
          "[<EntryPoint>]"
          "[<global.System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage>]"
          "let main args ="
          "    if Array.exists(fun arg -> arg = \"--server\" || arg = \"--internal-msbuild-node\") args then"
          "        global.Xunit.Runner.InProc.SystemConsole.TestingPlatform.TestPlatformTestFramework.RunAsync(args, System.Action<_,_>(fun b a -> SelfRegisteredExtensions.AddSelfRegisteredExtensions(b,a))).GetAwaiter().GetResult()"
          "    else"
          "        global.Xunit.Runner.InProc.SystemConsole.ConsoleRunner.Run(args).GetAwaiter().GetResult()" ]
        |> String.concat "\n"

    let private xunitV3 projectDirectory sources references =
        let sourceSet = Set.ofList sources

        let selfRegistered =
            Path.Combine(projectDirectory, "obj/Release/net10.0/SelfRegisteredExtensions.fs")

        let entryPoint =
            Path.Combine(projectDirectory, "obj/Release/net10.0/XunitAutoGeneratedEntryPoint.fs")

        let reporters = sources |> List.filter isXunitDefaultReporters

        let observed =
            Set.contains selfRegistered sourceSet
            || Set.contains entryPoint sourceSet
            || not reporters.IsEmpty

        if not observed then
            Ok Set.empty
        elif
            not (Set.contains selfRegistered sourceSet)
            || not (Set.contains entryPoint sourceSet)
            || not (
                hasReference
                    "/microsoft.testing.platform.msbuild/1.8.4/lib/net9.0/Microsoft.Testing.Extensions.MSBuild.dll"
                    references
                && hasReference "/xunit.v3.extensibility.core/3.1.0/lib/netstandard2.0/xunit.v3.core.dll" references
                && hasReference "/xunit.v3.runner.common/3.1.0/lib/netstandard2.0/xunit.v3.runner.common.dll" references
                && hasReference
                    "/xunit.v3.runner.inproc.console/3.1.0/lib/net8.0/xunit.v3.runner.inproc.console.dll"
                    references
            )
        then
            Error "BUILD003: The xUnit v3 generated-source profile is incomplete or has unsupported package identities."
        else
            match reporters with
            | [ reporter ] ->
                let selfText = text selfRegistered

                let namespacePrefix = "namespace "

                let rootNamespace =
                    selfText.Split('\n')
                    |> Array.tryFind (fun line -> line.StartsWith(namespacePrefix, StringComparison.Ordinal))
                    |> Option.map (fun line -> line.Substring namespacePrefix.Length)

                match rootNamespace with
                | None -> Error "BUILD003: Microsoft Testing Platform emitted an unsupported generated F# source."
                | Some rootNamespace when not (validNamespace rootNamespace) ->
                    Error "BUILD003: Microsoft Testing Platform emitted an unsupported generated F# namespace."
                | Some rootNamespace ->
                    let platformHook =
                        "global.Microsoft.Testing.Platform.MSBuild.TestingPlatformBuilderHook"

                    let junitHook = "global.Spekt.TestReporter.JUnit.TestingPlatformBuilderHook"

                    let hasJunit =
                        hasReference "/junitxml.testlogger/7.0.2/build/_common/Spekt.TestLogger.dll" references
                        && hasReference
                            "/junitxml.testlogger/7.0.2/build/_common/Microsoft.VisualStudio.TestPlatform.Extension.JUnit.Xml.TestLogger.dll"
                            references

                    let hooks =
                        if hasJunit then
                            [ platformHook; junitHook ]
                        else
                            [ platformHook ]

                    if
                        text reporter <> defaultRunnerReporters
                        || selfText <> testingPlatformExtensions rootNamespace hooks
                        || text entryPoint <> xunitEntryPoint rootNamespace
                    then
                        Error
                            "BUILD003: xUnit v3 or Microsoft Testing Platform emitted unsupported generated F# content."
                    else
                        Ok(Set.ofList [ selfRegistered; reporter; entryPoint ])
            | _ ->
                Error
                    "BUILD003: The xUnit v3 generated-source profile is incomplete or has unsupported package identities."

    let isAspireProjectMetadata (file: string) =
        let normalized = normalizedPath file

        normalized.Contains("/obj/Release/net10.0/Aspire/references/", StringComparison.Ordinal)
        && normalized.EndsWith(".ProjectMetadata.g.fs", StringComparison.Ordinal)

    let private generatedClassName (project: string) =
        let name =
            Path.GetFileNameWithoutExtension project
            |> Option.ofObj
            |> Option.defaultValue ""

        Regex.Replace(name, "(((?<=\\.)|^)(?=\\d)|\\W)", "_")

    let private canonicalPath path =
        let full = Path.GetFullPath path
        let root = Path.GetPathRoot full |> Option.ofObj |> Option.defaultValue ""

        let parts =
            full
                .Substring(root.Length)
                .Replace(Path.AltDirectorySeparatorChar, Path.DirectorySeparatorChar)
                .Split(Path.DirectorySeparatorChar, StringSplitOptions.RemoveEmptyEntries)
            |> Array.toList

        let rec resolve current remaining =
            match remaining with
            | [] -> current
            | part :: rest ->
                let next = Path.Combine(current, part)

                let resolved =
                    if
                        (Directory.Exists next || File.Exists next)
                        && File.GetAttributes(next) &&& FileAttributes.ReparsePoint = FileAttributes.ReparsePoint
                    then
                        if Directory.Exists next then
                            DirectoryInfo(next).ResolveLinkTarget(true)
                            |> FDull.Transport.External.required "generated-source.real-directory"
                            |> _.FullName
                        else
                            FileInfo(next).ResolveLinkTarget(true)
                            |> FDull.Transport.External.required "generated-source.real-file"
                            |> _.FullName
                    else
                        next

                resolve resolved rest

        resolve root parts |> Path.GetFullPath

    let private aspireProjectMetadata className projectPath =
        [ "namespace Projects"
          ""
          "[<global.System.Diagnostics.DebuggerDisplay(\"Type = {GetType().Name,nq}, ProjectPath = {ProjectPath}\")>]"
          "type " + className + "() ="
          "  member _.ProjectPath = \"\"\"" + projectPath + "\"\"\""
          "  interface global.Aspire.Hosting.IProjectMetadata with"
          "    member this.ProjectPath = this.ProjectPath"
          "" ]
        |> String.concat "\n"

    let private aspireHostMetadata className projectDirectory =
        [ "namespace Projects"
          ""
          "type internal " + className + "() ="
          "  member _.ProjectPath = \"\"\"" + projectDirectory + "\"\"\""
          "" ]
        |> String.concat "\n"

    let private aspire root projectDirectory project projectReferences sources references =
        let generated = sources |> List.filter isAspireProjectMetadata |> Set.ofList

        if generated.IsEmpty then
            Ok Set.empty
        elif
            not (
                hasReference "/aspire.hosting.apphost/13.4.6/lib/net10.0/Aspire.Hosting.AppHost.dll" references
                && hasReference "/aspire.hosting/13.4.6/lib/net8.0/Aspire.Hosting.dll" references
                && hasReference
                    "/fsharp.aspire.hosting.apphost/13.0.0/lib/net8.0/FSharp.Aspire.Hosting.AppHost.dll"
                    references
            )
        then
            Error "BUILD003: The Aspire generated-source profile has unsupported package identities."
        else
            let host =
                Path.Combine(projectDirectory, "obj/Release/net10.0/Aspire/references/_AppHost.ProjectMetadata.g.fs")

            let projects =
                projectReferences
                |> List.map (fun reference ->
                    let projectPath = Path.GetFullPath(reference, root)
                    let className = generatedClassName projectPath

                    Path.Combine(
                        projectDirectory,
                        "obj/Release/net10.0/Aspire/references/" + className + ".ProjectMetadata.g.fs"
                    ),
                    [ projectPath; canonicalPath projectPath ]
                    |> List.distinct
                    |> List.map (aspireProjectMetadata className))

            let expected = host :: (projects |> List.map fst) |> Set.ofList

            let hostDirectory = Path.TrimEndingDirectorySeparator projectDirectory

            let contents =
                (host,
                 [ hostDirectory; canonicalPath hostDirectory ]
                 |> List.distinct
                 |> List.map (aspireHostMetadata (generatedClassName project)))
                :: projects

            let validEncoding file =
                match File.ReadAllBytes file |> Array.toList with
                | 0xffuy :: 0xfeuy :: _ -> true
                | _ -> false

            if
                generated <> expected
                || contents
                   |> List.exists (fun (file, expectedText) ->
                       not (validEncoding file) || not (List.contains (text file) expectedText))
            then
                Error "BUILD003: Aspire emitted an unsupported generated F# project-metadata inventory."
            else
                Ok generated

    let supported root (projectDirectory: string) (project: string) projectReferences sources references =
        let sourceSet = Set.ofList sources

        let projectName =
            Path.GetFileNameWithoutExtension project
            |> Option.ofObj
            |> Option.defaultValue ""

        let standard =
            [ Path.Combine(projectDirectory, "obj/Release/net10.0/.NETCoreApp,Version=v10.0.AssemblyAttributes.fs")
              Path.Combine(projectDirectory, "obj/Release/net10.0/" + projectName + ".AssemblyInfo.fs")
              Path.Combine(
                  projectDirectory,
                  "obj/Release/net10.0/" + projectName + ".MvcApplicationPartsAssemblyInfo.fs"
              ) ]
            |> List.filter (fun file -> Set.contains file sourceSet)
            |> Set.ofList

        let testSdk = sources |> List.filter isTestSdkProgram |> Set.ofList

        match
            xunitV3 projectDirectory sources references,
            aspire root projectDirectory project projectReferences sources references
        with
        | Ok xunit, Ok aspire -> Ok(Set.union standard (Set.union testSdk (Set.union xunit aspire)))
        | Error error, _
        | _, Error error -> Error error
